version: "3.7"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9000"


# Portainer - Simplificando o gerenciamento dos containers docker
# https://youtu.be/11vgqPlMFuM

# portainer.io
# https://www.portainer.io/
