version: "3.7"

services:
  registry:
    image: registry
    container_name: registry
    volumes:
      - ${REGISTRY_VOL}:${REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY}
    tty: true
    ports:
      - 5000:5000
