version: "3.7"

services:
  vanellope:
    image: python:3.6-buster
    container_name: vanellope
    working_dir: /root/src
    env_file:
      - $HOME/projects/vanelope/.vscode/vanellope.env
    volumes:
      - $VANELLOPE_SRC:/root/src
    tty: true
    depends_on:
      - vanellope_db
      - vanellope_mock
    expose:
      - 8008
    ports:
      - 8008:8008
    command: >
      bash -c "apt update && 
      apt-get install -y python-psycopg2 && 
      pip install -U -r api/requirements/development.txt;  
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8008"
