version: "3.7"

services:
  dns:
    image: defreitas/dns-proxy-server
    container_name: dns
    hostname: dns.ti2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
      - /volumes/dns/config.json:/app/conf/config.json
    tty: true
    ports:
      - 5380:5380
