version: "3.7"

services:
  mkdocs:
    build:
      context: build/context/mkdocs
    container_name: mkdocs
    volumes:
      - ${MKDOCS_VOL}:/docs
    tty: true
    ports:
      - 8000:8000
    working_dir: /docs
    entrypoint:
      - mkdocs
      - serve
      - --dev-addr
      - 0.0.0.0:8000
      - --livereload
      - --dirtyreload
      - --verbose
