version: "3.7"
services:
  mysql_1:
    container_name: mysql_1
    image: mysql:5.7
    env_file:
      - .env
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    tty: true
    ports:
      - 3366:3306
