version: "3.7"

services:
  vanellope_mock:
    image: python:3.6-buster
    container_name: vanellope_mock
    working_dir: /root/src
    volumes:
      - $VANELLOPE_MOCK_SRC:/root/src
    tty: true
    expose:
      - 8000
    ports:
      - 8000:8000
    command: >
      bash -c "pip install mock-server; 
      mock-server --address=0.0.0.0 --port=8000 --dir=./api && python3
      "
