version: "3.7"
services:
  mysql_0:
    container_name: mysql_0
    image: mysql:5.5
    env_file:
      - .env
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    tty: true
    ports:
      - 3366:3306
