version: "3.7"
services:
  postgres_db0:
    container_name: postgres_db0
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db0
    tty: true
    ports:
      - 5432:5432