version: "3.7"

services:
  registry:
    image: registry
    container_name: registry
    volumes:
      - ${REGISTRY_VOL}:${REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY}
    tty: true
    ports:
      - 5000:5000

# https://docs.docker.com/registry/
# https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-18-04
