version: "3.7"
services:
  mikedb:
    container_name: mikedb
    image: postgres
    tty: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MIKE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MIKE}
      - POSTGRES_DB=${POSTGRES_DB_MIKE}
    ports:
       - "5432:5432"
